### ISSUE TITLE
Apple Watch

### ISSUE THREAD

**Issue by pdp2015** [anverbogatov/OpenWeatherMapKit#1]
Hi any dates for releasing apple watch app yet?

Many thanks

**Comment by anverbogatov** [comment]
Hi there,

I am going to add support of 5 days forecast this weekend, but still - no dates for watchOS. Sorry.

**Comment by anverbogatov** [comment]
Hi there,

I have released OpenWeatherMapKit 0.2.
I have added watchOS support to framework’s podspec file. Since the framework does not use anything specific for iOS - it should help with running it as part of watchOS app.
So, you can try it in your watchOS app.

**Comment by pdp2015** [comment]
I dont have a watch app built as yet was going to wait to see how yours looks

**Comment by anverbogatov** [comment]
Oh, sorry then. I did not understand that you were looking for the app.
In that case, I can say that this repository contains only sources related to swift framework that was originally developed to provide Open Weather Map functions access. And I did not plan to write full watchOS weather app.

**Comment by pdp2015** [comment]
No thats fine was my mistake. Was looking at the PI Weather app on github the other day and thiuggt that apple watch app screen looks really good so trying to find out about changing it so it would work with openweather Api
