### ISSUE TITLE
GetCurrentWeather Decoding Error

### ISSUE THREAD

**Issue by remoreichsoellner** [anverbogatov/OpenWeatherMapKit#7]
Optional(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "deg", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "wind", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"deg\", intValue: nil) (\"deg\").", underlyingError: nil)))

This error happens only sometimes and i cant figure out where it really happens.

**Comment by anverbogatov** [comment]
Thanks for reporting the problem. 
Can you add code sample of the call that may give you the error? Also, it would be very useful if you will add exact json response that was given by Open Weather API. Looks like there was something else instead of valid response.

**Comment by remoreichsoellner** [comment]
Thanks for your response!

I used the sample code you provided on the gitHub page to get the current weather by geo coordinates:

OpenWeatherMapKit.instance.currentWeather(forCoordiante: (latitude: 53.2610313, longitude: 50.0579958)) { (forecast, error) in
    ...
}
The problem is that the forecast element is nil because of the error i posted, so the app crashes every time the code runs. I tried to call the generated URL (printed out in console by your code) manually via Postman and it returned a valid response of the api. 

I think the problem is that sometimes the openweathermap API has no data about the wind values, etc. but you don’t check that in your code and try to assign an element that doesn’t even exist in every API call (please correct me if this isn’t true).

- HerrBumseBiene

**Comment by anverbogatov** [comment]
Author no longer maintain that project. Issue is closed.
