### ISSUE TITLE
use 'addingPercentEncoding' before calling in 'get<T : Codable>[....]'

### ISSUE THREAD

**Issue by Mamonaku** [anverbogatov/OpenWeatherMapKit#8]
Hi,
When the city name has a blank space, the URL() call fails, and get<T> returns without calling OpenWeatherMap API. Therefore, in

`    internal func get<T : Codable>(from url: String, callback: @escaping (T?, Error?) -> ()) 
`

 instead of:

```
        guard  let serviceUrl = URL(string:url) else {
            return
        }
```
You could add something along the lines:
```
        guard let encoded = url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed), let serviceUrl = URL(string:encoded) else {
            callback(nil, NSError(domain: "OpenWeatherMap.NetworkManager", code: -1, userInfo: [NSLocalizedDescriptionKey:"Could not encode \(url)"]))
            return
        }

```
thanks!

**Comment by anverbogatov** [comment]
Author no longer maintain that project. Issue is closed.
